### ISSUE TITLE
Using baremetal provider from behind an explicit proxy times out

### ISSUE THREAD

**Issue by PeterJamesHarrison** [oracle/terraform-provider-baremetal#48] opened 2017-03-30 08:54 UTC
Is there support for an explicit proxy supporting the environment variables like: 
export http_proxy=http://internal-web-proxy.example.com:80
export https_proxy=http://internal-web-proxy.example.com:80

Currently when behind a proxy server it just times out and does not appear to utilise the proxy environment variables.
From checking elsewhere it appears to need to be supported in the provider code not base Terraform code.

**Comment by mikejihbe** [comment] 2017-03-31 16:33
https://github.com/hashicorp/terraform/issues/523#issuecomment-108627088

**Comment by mrhearn** [comment] 2017-04-03 12:54
v1.0.5  - Experiencing crashes with or without http_proxy or https:_proxy being set.
e.g.
panic: runtime error: invalid memory address or nil pointer dereference

2017/04/03 06:41:21 [DEBUG] plugin: terraform-provider-baremetal_amd64: [signal SIGSEGV: segmentation violation code=0x1 addr=0x48 pc=0x939bbb]
2017/04/03 06:41:21 [DEBUG] plugin: terraform-provider-baremetal_amd64:
2017/04/03 06:41:21 [DEBUG] plugin: terraform-provider-baremetal_amd64: goroutine 46 [running]:
2017/04/03 06:41:21 [DEBUG] plugin: terraform-provider-baremetal_amd64: github.com/oracle/terraform-provider-baremetal/vendor/github.com/MustWin/baremetal-sdk-go.(*apiRequestor).request(0xc420424780, 0xb46bc5, 0x4, 0xee2760, 0xc42023caa0, 0xa42c00, 0xc4203c0d20, 0xa42c00)
2017/04/03 06:41:21 [DEBUG] plugin: terraform-provider-baremetal_amd64:         /Users/ccarl/my/code/GOPATH/src/github.com/oracle/src/github.com/oracle/terraform-provider-baremetal/vendor/github.com/MustWin/baremetal-sdk-go/requestor.go:146 +0x4bb
2017/04/03 06:41:21 [DEBUG] plugin: terraform-provider-baremetal_amd64: github.com/oracle/terraform-provider-baremetal/vendor/github.com/MustWin/baremetal-sdk-go.(*Client).CreateVolume(0xc420350d00, 0xc4203c0b50, 0xd, 0xc4203b2480, 0x53, 0xc4203c4d40, 0xf1b420, 0xb43900, 0xb44de8)
2017/04/03 06:41:21 [DEBUG] plugin: terraform-provider-baremetal_amd64:         /Users/ccarl/my/code/GOPATH/src/github.com/oracle/src/github.com/oracle/terraform-provider-baremetal/vendor/github.com/MustWin/baremetal-sdk-go/core_volume.go:53 +0x143
2017/04/03 06:41:21 [DEBUG] plugin: terraform-provider-baremetal_amd64: github.com/oracle/terraform-provider-baremetal/core.(*VolumeResourceCrud).Create(0xc4203c66a0, 0x0, 0x20)
2017/04/03 06:41:21 [DEBUG] plugin: terraform-provider-baremetal_amd64:         /Users/ccarl/my/code/GOPATH/src/github.com/oracle/src/github.com/oracle/terraform-provider-baremetal/core/volume_resource_crud.go:58 +0x283
2017/04/03 06:41:21 [DEBUG] plugin: terraform-provider-baremetal_amd64: github.com/oracle/terraform-provider-baremetal/crud.CreateResource(0xc4203b2540, 0xee3ba0, 0xc4203c66a0, 0x7fa96a330160, 0xc420350d00)
2017/04/03 06:41:21 [DEBUG] plugin: terraform-provider-baremetal_amd64:         /Users/ccarl/my/code/GOPATH/src/github.com/oracle/src/github.com/oracle/terraform-provider-baremetal/crud/helpers.go:64 +0x49
2017/04/03 06:41:21 [DEBUG] plugin: terraform-provider-baremetal_amd64: github.com/oracle/terraform-provider-baremetal/core.createVolume(0xc4203b2540, 0xb44da0, 0xc420350d00, 0x18, 0x40bba4)
2017/04/03 06:41:21 [DEBUG] plugin: terraform-provider-baremetal_amd64:         /Users/ccarl/my/code/GOPATH/src/github.com/oracle/src/github.com/oracle/terraform-provider-baremetal/core/volume_resource.go:64 +0xe0
2017/04/03 06:41:21 [DEBUG] plugin: terraform-provider-baremetal_amd64: github.com/oracle/terraform-provider-baremetal/vendor/github.com/hashicorp/terraform/helper/schema.(*Resource).Apply(0xc42040e900, 0xc42023ca00, 0xc4203c6620, 0xb44da0, 0xc420350d00, 0x1, 0x28, 0xc420387d40)
2017/04/03 06:41:21 [DEBUG] plugin: terraform-provider-baremetal_amd64:         /Users/ccarl/my/code/GOPATH/src/github.com/oracle/src/github.com/oracle/terraform-provider-baremetal/vendor/github.com/hashicorp/terraform/helper/schema/resource.go:162 +0x2d0
2017/04/03 06:41:21 [DEBUG] plugin: terraform-provider-baremetal_amd64: github.com/oracle/terraform-provider-baremetal/vendor/github.com/hashicorp/terraform/helper/schema.(*Provider).Apply(0xc42040ee40, 0xc42023c9b0, 0xc42023ca00, 0xc4203c6620, 0x7fa96a404e10, 0x0, 0x0)
2017/04/03 06:41:21 [DEBUG] plugin: terraform-provider-baremetal_amd64:         /Users/ccarl/my/code/GOPATH/src/github.com/oracle/src/github.com/oracle/terraform-provider-baremetal/vendor/github.com/hashicorp/terraform/helper/schema/provider.go:212 +0x9b
2017/04/03 06:41:21 [DEBUG] plugin: terraform-provider-baremetal_amd64: github.com/oracle/terraform-provider-baremetal/vendor/github.com/hashicorp/terraform/plugin.(*ResourceProviderServer).Apply(0xc4203e21e0, 0xc4203c6100, 0xc4203c0c10, 0x0, 0x0)
2017/04/03 06:41:21 [DEBUG] plugin: terraform-provider-baremetal_amd64:         /Users/ccarl/my/code/GOPATH/src/github.com/oracle/src/github.com/oracle/terraform-provider-baremetal/vendor/github.com/hashicorp/terraform/plugin/resource_provider.go:488 +0x57
2017/04/03 06:41:21 [DEBUG] plugin: terraform-provider-baremetal_amd64: reflect.Value.call(0xc42027c2a0, 0xc4201ac438, 0x13, 0xb46a89, 0x4, 0xc420206f20, 0x3, 0x3, 0x43808c, 0xc420027738, ...)
2017/04/03 06:41:21 [DEBUG] plugin: terraform-provider-baremetal_amd64:         /usr/local/go/src/reflect/value.go:434 +0x91f
2017/04/03 06:41:21 [DEBUG] plugin: terraform-provider-baremetal_amd64: reflect.Value.Call(0xc42027c2a0, 0xc4201ac438, 0x13, 0xc420027720, 0x3, 0x3, 0x0, 0x180000, 0x0)
2017/04/03 06:41:21 [DEBUG] plugin: terraform-provider-baremetal_amd64:         /usr/local/go/src/reflect/value.go:302 +0xa4
2017/04/03 06:41:21 [DEBUG] plugin: terraform-provider-baremetal_amd64: net/rpc.(*service).call(0xc4203e8580, 0xc4203e8540, 0xc4203ea2b0, 0xc4202b6080, 0xc4203e29c0, 0xa276e0, 0xc4203c6100, 0x16, 0xa27720, 0xc4203c0c10, ...)
2017/04/03 06:41:21 [DEBUG] plugin: terraform-provider-baremetal_amd64:         /usr/local/go/src/net/rpc/server.go:387 +0x144
2017/04/03 06:41:21 [DEBUG] plugin: terraform-provider-baremetal_amd64: created by net/rpc.(*Server).ServeCodec
2017/04/03 06:41:21 [DEBUG] plugin: terraform-provider-baremetal_amd64:         /usr/local/go/src/net/rpc/server.go:481 +0x404
2017/04/03 06:41:21 [DEBUG] plugin: /app/terraform/providers/terraform-provider-baremetal_amd64: plugin process exited
2017/04/03 06:41:21 [DEBUG] root: eval: *terraform.EvalWriteState
2017/04/03 06:41:21 [DEBUG] root: eval: *terraform.EvalApplyProvisioners
2017/04/03 06:41:21 [DEBUG] root: eval: *terraform.EvalIf
2017/04/03 06:41:21 [DEBUG] root: eval: *terraform.EvalWriteState
2017/04/03 06:41:21 [DEBUG] root: eval: *terraform.EvalWriteDiff
2017/04/03 06:41:21 [DEBUG] root: eval: *terraform.EvalApplyPost
2017/04/03 06:41:21 [DEBUG] root: eval: *terraform.EvalWriteState
2017/04/03 06:41:21 [ERROR] root: eval: *terraform.EvalApplyPost, err: 1 error(s) occurred:

* baremetal_core_instance.terra_test_1-gitbmc000009: unexpected EOF
2017/04/03 06:41:21 [ERROR] root: eval: *terraform.EvalSequence, err: 1 error(s) occurred:

* baremetal_core_instance.terra_test_1-gitbmc000009: unexpected EOF
2017/04/03 06:41:21 [TRACE] [walkApply] Exiting eval tree: baremetal_core_instance.terra_test_1-gitbmc000009
2017/04/03 06:41:21 [DEBUG] vertex "data.baremetal_core_vnic_attachments.terra_test_1-gitbmc000009-vnics", got dep: "baremetal_core_instance.terra_test_1-gitbmc000009"
2017/04/03 06:41:21 [DEBUG] vertex "data.baremetal_core_vnic.terra_test_1-gitbmc000009-vnic0", got dep: "data.baremetal_core_vnic_attachments.terra_test_1-gitbmc000009-vnics"
2017/04/03 06:41:21 [DEBUG] vertex "null_resource.terra_test_1-gitbmc000009", got dep: "data.baremetal_core_vnic.terra_test_1-gitbmc000009-vnic0"
2017/04/03 06:41:21 [DEBUG] vertex "meta.count-boundary (count boundary fixup)", got dep: "null_resource.terra_test_1-gitbmc000009"
2017/04/03 06:41:21 [DEBUG] vertex "meta.count-boundary (count boundary fixup)", got dep: "var.appowners"
2017/04/03 06:41:21 [DEBUG] vertex "meta.count-boundary (count boundary fixup)", got dep: "var.iscsi_ipport"
2017/04/03 06:41:21 [DEBUG] vertex "meta.count-boundary (count boundary fixup)", got dep: "var.bootstrap_common"
2017/04/03 06:41:21 [DEBUG] root: eval: *terraform.EvalApplyProvisioners
2017/04/03 06:41:21 [DEBUG] root: eval: *terraform.EvalIf
2017/04/03 06:41:21 [DEBUG] root: eval: *terraform.EvalWriteState
2017/04/03 06:41:21 [DEBUG] root: eval: *terraform.EvalWriteDiff
2017/04/03 06:41:21 [DEBUG] root: eval: *terraform.EvalApplyPost
2017/04/03 06:41:21 [ERROR] root: eval: *terraform.EvalApplyPost, err: 1 error(s) occurred:

* baremetal_core_volume.gitbmcblk000009-slot00: unexpected EOF
2017/04/03 06:41:21 [ERROR] root: eval: *terraform.EvalSequence, err: 1 error(s) occurred:

* baremetal_core_volume.gitbmcblk000009-slot00: unexpected EOF
2017/04/03 06:41:21 [TRACE] [walkApply] Exiting eval tree: baremetal_core_volume.gitbmcblk000009-slot00
2017/04/03 06:41:21 [DEBUG] vertex "baremetal_core_volume_attachment.gitbmcblk000009-slot00-attach", got dep: "baremetal_core_volume.gitbmcblk000009-slot00"
2017/04/03 06:41:21 [DEBUG] vertex "baremetal_core_volume_attachment.gitbmcblk000009-slot00-attach", got dep: "baremetal_core_instance.terra_test_1-gitbmc000009"
2017/04/03 06:41:21 [DEBUG] vertex "meta.count-boundary (count boundary fixup)", got dep: "baremetal_core_volume_attachment.gitbmcblk000009-slot00-attach"
2017/04/03 06:41:21 [DEBUG] vertex "meta.count-boundary (count boundary fixup)", got dep: "var.mntpoints"
2017/04/03 06:41:21 [DEBUG] vertex "meta.count-boundary (count boundary fixup)", got dep: "var.addon_packages01"
2017/04/03 06:41:21 [TRACE] Preserving existing state lineage "6ac2da2a-8778-400c-82a8-70707b98b0a3"
2017/04/03 06:41:21 [TRACE] Preserving existing state lineage "6ac2da2a-8778-400c-82a8-70707b98b0a3"
2017/04/03 06:41:21 [DEBUG] plugin: waiting for all plugin processes to complete...
2017/04/03 06:41:21 [WARN] plugin: error closing client during Kill: connection is shut down
2017/04/03 06:41:21 [DEBUG] plugin: terraform088: template-provider (internal) 2017/04/03 06:41:21 [DEBUG] plugin: waiting for all plugin processes to complete...
2017/04/03 06:41:21 [DEBUG] plugin: terraform088: remote-exec-provisioner (internal) 2017/04/03 06:41:21 [DEBUG] plugin: waiting for all plugin processes to complete...
2017/04/03 06:41:21 [DEBUG] plugin: terraform088: null-provider (internal) 2017/04/03 06:41:21 [DEBUG] plugin: waiting for all plugin processes to complete...
2017/04/03 06:41:21 [DEBUG] plugin: /app/terraform/bin/terraform088: plugin process exited
2017/04/03 06:41:21 [DEBUG] plugin: /app/terraform/bin/terraform088: plugin process exited
2017/04/03 06:41:21 [DEBUG] plugin: /app/terraform/bin/terraform088: plugin process exited



!!!!!!!!!!!!!!!!!!!!!!!!!!! TERRAFORM CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!

Terraform crashed! This is always indicative of a bug within Terraform.
A crash log has been placed at "crash.log" relative to your current
working directory. It would be immensely helpful if you could please
report the crash with Terraform[1] so that we can fix this.

When reporting bugs, please include your terraform version. That
information is available on the first line of crash.log. You can also
get it by running 'terraform --version' on the command line.

[1]: https://github.com/hashicorp/terraform/issues

!!!!!!!!!!!!!!!!!!!!!!!!!!! TERRAFORM CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!

**Comment by mikejihbe** [comment] 2017-04-03 16:56
I'm not able to reproduce this, but there is an edge case wherein we didn't check for errrors. If you run this with  `export DEBUG=true`, do your results change? Ideally you should get a log line with an error at least.

**Comment by mikejihbe** [comment] 2017-04-03 16:56
Also, please post your .tf file. I tried a volume attachment, but maybe there's different options or something.

**Comment by craigcarl-oracle** [comment] 2017-04-06 16:19
Bump

**Comment by craigcarl-oracle** [comment] 2017-04-11 16:23
Haven't been able to repo internally; need to setup a more restrictive proxy.

**Comment by mrhearn** [comment] 2017-04-11 16:31
Have not been able to reproduce the issue over the past few days.    Access to api via proxy seems to be stable for now.

**Comment by craigcarl-oracle** [comment] 2017-04-11 16:54
@mrhearn Excellent! I'll close the ticket, please reopen it if the issue resurfaces.

**Closed by craigcarl-oracle** 2017-04-11 16:54 UTC
Labels: bug, P1
