### ISSUE TITLE
Error while re-running same template file for Complete VCN creation.

### ISSUE THREAD

**Issue by rahulviswam17** [oracle/terraform-provider-baremetal#88] opened 2017-05-03 03:17 UTC
## Description of the bug:
Terraform errors out while trying to run "terraform apply" for the same template file for complete VCN. 

Error Message :

  dhcp_options_id: "ocid1.dhcpoptions.oc1.phx.aaaaaaaaa5hqwyrwq7n42l6jufr57hlpmr53apoewa7hvucriobfleq5h5ua" => ""
Error applying plan:

1 error(s) occurred:

* baremetal_core_subnet.WebSubnetAD1: Code: NotAuthorizedOrNotFound; OPC Request ID: /74731E3503244EC88F08D661B331E0D5/4E7EF0D68771427496B746F309490A60; Message: Either Subnet with ID ocid1.tenancy.oc1..aaaaaaaazqe56p5uw4ri7hzvmblb6jzwiuw6mdt7xgllx4vug3ttbyjtjuxq does not exist or you are not authorized to access it.

Terraform does not automatically rollback in the face of errors.
Instead, your Terraform state file has been partially updated with
any resources that successfully completed. Please address the error
above and apply again to incrementally change your infrastructure.

## A self-contained terraform file that reproduces the issue:

The OCID referenced in the error message is a compartment_ocid in real. I am not sure why is trying to map it against a subnetID.

[complete_vcn_network.txt](https://github.com/oracle/terraform-provider-baremetal/files/972401/complete_vcn_network.txt)

**Comment by craigcarl-oracle** [comment] 2017-05-03 03:56
@rahulviswam17 take a look at #64, there is a workaround in the thread while we work on a fix. 

Dupe of #64.

**Closed by craigcarl-oracle** 2017-05-03 03:56 UTC
