### ISSUE TITLE
Destroy should observe dependencies 

### ISSUE THREAD

**Issue by craigcarl-oracle** [oracle/terraform-provider-baremetal#142] opened 2017-06-07 01:02 UTC
@mikejihbe @josephholsten I've had multiple reports of the provider ignoring dependencies on destroy, it just retries every delete until they succeeded. The provider should observe dependencies  on destroy the same (inverse) as it does on apply.

**Comment by mikejihbe** [comment] 2017-06-07 01:03
This should be happening automatically. Do you have an example?

**Comment by mikejihbe** [comment] 2017-06-07 01:07
Just to clarify, terraform itself builds a dependency tree and handles ordering. Nothing in the provider does this.

**Comment by craigcarl-oracle** [comment] 2017-06-07 01:18
These reports are coming from the service teams, when a destroy is run we're not seeing any order of operations, in parallel (near enough) we receive delete API calls for VCN, subnets, compute, block, block attachments, etc. You should be able to observe this using any of the larger examples (try MongoDB) and setting up a proxy, I use mitmproxy.org.

**Comment by mikejihbe** [comment] 2017-06-07 03:35
Deletions do happen in parallel (this is a configurable terraform flag). 

Basically the destroy workflow is this:
1) Refresh all objects in the statefile
2) Of the objects that exist, build a dependency tree. Terraform uses implicit dependencies in the configuration to do this
3) Traverse the tree, when you reach a leaf, delete it
4) When a deletion is done, move to the parent. Check for dependencies, if there are any, repeat 2) from this point

It's a classic directed acyclic graph traversal.

So yes, any object, regardless of type, will be deleted if it has no dependencies immediately.

Here's a `mitmproxy` screenshot of the delete requests that happen to destroy the mongoDB example.

<img width="1321" alt="terraform-provider-baremetal_ _vi_resource_obmcs_loadbalancer_loadbalancer_go_ _python3_6__usr_local_bin_mitmproxy_ _164x39_and_destroy_should_observe_dependencies_ _issue__142_ _oracle_terraform-provider-baremetal" src="https://user-images.githubusercontent.com/52534/26861101-81ada3a8-4af6-11e7-8526-49a27ca28eee.png">


In this example, the PublicSubnetAD1 is deleted first because nothing uses it. All 3 instances are destroyed concurrently. Then things unwind as you would expect them to.

**Comment by craigcarl-oracle** [comment] 2017-06-07 03:41
Is TF waiting for the instances to transition to terminated before deleting the subnets?

**Comment by josephholsten** [comment] 2017-06-07 04:25
The code is written to retry while in [state: terminating](https://github.com/oracle/terraform-provider-baremetal/blob/master/resource_obmcs_core_instance.go#L186) and move on when it reaches [state: terminated](https://github.com/oracle/terraform-provider-baremetal/blob/master/resource_obmcs_core_instance.go#L190).

I haven't set up proxy or debug logs to verify this behavior is occurring, but that definitely is the intent.

@mikejihbe do you have those logs handy or shall I attempt to record this?

**Comment by mikejihbe** [comment] 2017-06-07 04:31
Yes, that is how it works. All of this is apparent in debug logs. Here's the proof:

9549 - MongoDBAD2 - Terminated

<img width="1312" alt="banners_and_alerts_and_mongodb_ _vim___downloads_full-destroy_log_ _vim___downloads_full-destroy_log_ _164x38" src="https://user-images.githubusercontent.com/52534/26862276-bd1bd2d6-4afe-11e7-998e-e9ca1fc39203.png">

9637 - PrivSubnetAD2 - Start destroy (THIS IS FINE, because MongoDBAD2 was the only thing depending on it)

<img width="1302" alt="mongodb_ _vim___downloads_full-destroy_log_ _vim___downloads_full-destroy_log_ _164x38" src="https://user-images.githubusercontent.com/52534/26862327-31a1c908-4aff-11e7-8287-c726f274a77a.png">



9679 - MongoDB-Bastion - Terminated

<img width="1311" alt="banners_and_alerts_and_mongodb_ _vim___downloads_full-destroy_log_ _vim___downloads_full-destroy_log_ _164x38" src="https://user-images.githubusercontent.com/52534/26862286-d548017c-4afe-11e7-8153-dbd7a514aa3a.png">


9732 - MongoDBAD1 - Terminated
<img width="1306" alt="banners_and_alerts_and_mongodb_ _vim___downloads_full-destroy_log_ _vim___downloads_full-destroy_log_ _164x38" src="https://user-images.githubusercontent.com/52534/26862259-928b75a8-4afe-11e7-9fc9-fd3ffb94ae2b.png">


9871 - BastionSubnetAD1 - Start destroy

<img width="1315" alt="mongodb_ _vim___downloads_full-destroy_log_ _vim___downloads_full-destroy_log_ _164x38" src="https://user-images.githubusercontent.com/52534/26862298-f15c5b4c-4afe-11e7-82bb-626e8c4ce1ff.png">

9945 - PrivSubnetAD1 - Start destroy

<img width="1316" alt="mongodb_ _vim___downloads_full-destroy_log_ _vim___downloads_full-destroy_log_ _164x38" src="https://user-images.githubusercontent.com/52534/26862306-02fad432-4aff-11e7-82d4-75a1e48f98a0.png">

**Comment by mikejihbe** [comment] 2017-06-07 04:58
I think you're going to have to give me something reproducible for me to help you here. Everything is designed to do this correctly and terraforms number one job is understanding dependencies.

Is there a symptom other than "things seem to happen out of order"?

**Comment by craigcarl-oracle** [comment] 2017-06-07 06:25
Let me try and repro the behaviour engineering is describing.

**Comment by codycushing** [comment] 2017-06-29 17:58
It's possible someone did this by explicitly setting dependent values between resources rather than using interpolation syntax, in that case they would need to specify the dependencies. I don't think there is anything to do here, closing until a concrete case is discovered.

**Closed by codycushing** 2017-06-29 17:58 UTC
Labels: question
